import 'package:gestor/domain/entities/global_user.dart';
import 'package:gestor/domain/entities/teachers.dart';

final GlobalUser test_user_data = GlobalUser(
    nombre: 'Pepito',
    boleta: '1234567890',
    curp: 'XD',
    imageUrl:
        'https://st3.depositphotos.com/6672868/13701/v/450/depositphotos_137014128-stock-illustration-user-profile-icon.jpg',
    subjects: [
      AssignedTeacher(
          teacherID: '1',
          firstName: 'Maestro Bot',
          lastName: 'Profesor',
          curp: '55123456789',
          academyName: 'Electónica',
          group: '5CM1',
          subject: 'Procesamiento Digital de Señales'),
      AssignedTeacher(
          teacherID: '2',
          firstName: 'Maestro 2',
          lastName: 'Profesor chafa',
          curp: '55123456789',
          academyName: 'Mantenido',
          group: 'XXX3',
          subject: 'Mendigar'),
      AssignedTeacher(
          teacherID: '3',
          firstName: 'Pepe',
          lastName: 'Arriba',
          curp: '55123456789',
          academyName: 'Abajo',
          group: '4AM2',
          subject: 'No se sabe'),
      AssignedTeacher(
          teacherID: '4',
          firstName: 'Otro maestro más',
          lastName: 'maistro',
          curp: '55123456789',
          academyName: 'Sonidero',
          group: '6CM7',
          subject: 'Sistemas en Chip'),
      AssignedTeacher(
          teacherID: '5',
          firstName: 'Maestro Bot',
          lastName: 'Profesor',
          curp: '55123456789',
          academyName: 'Electónica',
          group: '5CM1',
          subject: 'Procesamiento Digital de Señales'),
      AssignedTeacher(
          teacherID: '6',
          firstName: 'Maestro Bot',
          lastName: 'Profesor',
          curp: '55123456789',
          academyName: 'Electónica',
          group: '5CM1',
          subject: 'Procesamiento Digital de Señales'),
      AssignedTeacher(
          teacherID: '7',
          firstName: 'Maestro Bot',
          lastName: 'Profesor',
          curp: '55123456789',
          academyName: 'Electónica',
          group: '5CM1',
          subject: 'Procesamiento Digital de Señales'),
    ]);

final List<Map<String, dynamic>> testSchedule = [
  {
    "GroupCode": "G101",
    "UnitName": "Mathematics",
    "DayOfWeek": "Lunes",
    "StartTime": "8:30",
    "EndTime": "10:00",
    "Classroom": "Room 101",
    "Lab": null,
  },
  {
    "GroupCode": "G101",
    "UnitName": "Mathematics",
    "DayOfWeek": "Viernes",
    "StartTime": "8:30",
    "EndTime": "10:00",
    "Classroom": "Room 101",
    "Lab": null,
  },
  {
    "GroupCode": "G101",
    "UnitName": "Mathematics",
    "DayOfWeek": "Martes",
    "StartTime": "8:30",
    "EndTime": "10:00",
    "Classroom": "Room 101",
    "Lab": null,
  },
  {
    "GroupCode": "G101",
    "UnitName": "Mathematics",
    "DayOfWeek": "Miercoles",
    "StartTime": "8:30",
    "EndTime": "10:00",
    "Classroom": "Room 101",
    "Lab": null,
  },
  {
    "GroupCode": "G201",
    "UnitName": "Physics",
    "DayOfWeek": "Jueves",
    "StartTime": "10:30",
    "EndTime": "12:00",
    "Classroom": "Room 202",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "G203",
    "UnitName": "Formulación y Evaluación de Proyectos Informáticos",
    "DayOfWeek": "Viernes",
    "StartTime": "10:30",
    "EndTime": "12:00",
    "Classroom": "Room 202",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "G205",
    "UnitName": "Comedia",
    "DayOfWeek": "Martes",
    "StartTime": "7:00",
    "EndTime": "8:30",
    "Classroom": "Room 202",
    "Lab": "Lab A",
  },
  {
    "GroupCode": "G205",
    "UnitName": "Relleno",
    "DayOfWeek": "Miercoles",
    "StartTime": "16:30",
    "EndTime": "18:00",
    "Classroom": "Room 202",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "G205",
    "UnitName": "Relleno",
    "DayOfWeek": "Miercoles",
    "StartTime": "16:30",
    "EndTime": "18:00",
    "Classroom": "Room 202",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "G205",
    "UnitName": "Relleno",
    "DayOfWeek": "Lunes",
    "StartTime": "13:30",
    "EndTime": "15:00",
    "Classroom": "Room 202",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "6CM2",
    "UnitName": "La clase del Lorem IPSUM",
    "DayOfWeek": "Jueves",
    "StartTime": "20:00",
    "EndTime": "21:30",
    "Classroom": "2105",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "6CM2",
    "UnitName": "La clase del Lorem IPSUM",
    "DayOfWeek": "Martes",
    "StartTime": "16:30",
    "EndTime": "20:00",
    "Classroom": "2105",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "6CM2",
    "UnitName": "La clase del Lorem IPSUM",
    "DayOfWeek": "Miercoles",
    "StartTime": "16:30",
    "EndTime": "20:00",
    "Classroom": "2105",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "6CM1",
    "UnitName": "Una clase random",
    "DayOfWeek": "Viernes",
    "StartTime": "10:30",
    "EndTime": "12:00",
    "Classroom": "2105",
    "Lab": "Lab A",
  },
  {
    "GroupCode": "6CM1",
    "UnitName": "Una clase random",
    "DayOfWeek": "Jueves",
    "StartTime": "12:00",
    "EndTime": "13:30",
    "Classroom": "2105",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "6CM1",
    "UnitName": "Madrugadora",
    "DayOfWeek": "Martes",
    "StartTime": "20:00",
    "EndTime": "21:30",
    "Classroom": "2105",
    "Lab": "Lab A",
  },
  {
    "GroupCode": "6CM1",
    "UnitName": "Madrugadora",
    "DayOfWeek": "Miercoles",
    "StartTime": "7:00",
    "EndTime": "8:30",
    "Classroom": "2105",
    "Lab": "Lab A",
  },

  {
    "GroupCode": "6CM1",
    "UnitName": "Madrugadora",
    "DayOfWeek": "Jueves",
    "StartTime": "18:30",
    "EndTime": "20:00",
    "Classroom": "2105",
    "Lab": "Lab A",
  },
  // Agregar más elementos si se necesita un horario más largo
];
